# Generated by Django 6.0.5 on 2026-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enquiry_alter_gallery_options_announcement_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videolecture',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
